SHELL=/bin/bash -x

all:
	sudo apt-get -y install openjdk-8-jdk
	# Install hadoop
	/apps/resources/hadoop/install.sh

	# Install spark
	/apps/resources/spark/install.sh

	# Install hive
	/apps/resources/hive/install.sh

