SHELL=/bin/bash -x

all:
	sudo apt-get -y install openjdk-8-jdk
	# Install hadoop
	/apps/conf/hadoop/install.sh

	# Install spark
	/apps/conf/spark/install.sh

	# Install hive
	/apps/conf/hive/install.sh

