#!/bin/bash
# pitest 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    /cluster/hadoop/bin/hdfs dfsadmin -report

    /cluster/spark/bin/spark-submit --class org.apache.spark.examples.streaming.NetworkWordCount \
    --deploy-mode client /cluster/spark/examples/jars/spark-examples*.jar localhost 45000

}
